main: cn.eggpixel.Main
name: EmeraldTools
version: 2.0.0
author: EmeraldsEgg
api-version: 1.15

commands:
  df:
    usage: /<command> [World] [true/false]
    description: Disable flying in a world.
    permission: emeraldtools.true
    permission-message: '§cYou do not have permission to do this!'
  ab:
    usage: /<command> [World] [true/false]
    description: Anti-Build in a world.
    permission: emeraldtools.true
    permission-message: '§cYou do not have permission to do this!'
  heal:
    usage: /<command> [Player]
    description: Heal a player.
    permission: emeraldtools.true
    permission-message: '§cYou do not have permission to do this!'
  ad:
    usage: /<command>
    description: Anti-Drop.
    permission: emeraldtools.true
    permission-message: '§cYou do not have permission to do this!'
  fly:
    usage: /<command> [Player]
    description: Flight
    permission: emeraldtools.true
    permission-message: '§cYou do not have permission to do this!'
  prefix:
    usage: /<command> <Player> <add/remove> [prefix]
    description: Give a player a prefix
    permission: emeraldtools.true
    permission-message: '§cYou do not have permission to do this!'
  repair:
    usage: /<command> [on/off]
    description: If player does not have permission,they will kicked
    permission: emeraldtools.true
    permission-message: '§cYou do not have permission to do this!'
permissions:
  emeraldtools.main:
    default: op
    children:
      antibuild.admin: true
      disableflying.admin: true
      emeraldtools.heal: true
      emeraldtools.antidrop: true
      emeraldtools.fly: true
      emeraldtools.lagremover: true
      emeraldtools.ban: true
      emeraldtools.addprefix: true
      emeraldtools.repair: true
  antibuild.admin:
    default: op
    children:
      antibuild.place: true
      antibuild.destroy: true
      antibuild.attack: true
  disableflying.admin:
    default: op
    children:
      disableflying.fly: true
  emeraldtools.true:
    default: true
  disableflying.fly:
    default: op
  antibuild.place:
    default: op
  antibuild.destroy:
    default: op
  antibuild.attack:
    default: op
  emeraldtools.heal:
    default: op
  emeraldtools.antidrop:
    default: true
  emeraldtools.fly:
    default: op
  emeraldtools.addprefix:
    default: op
  emeraldtools.repair:
    default: op
    children:
      emeraldtools.repair.join: true
  emeraldtools.repair.join:
    default: op
    description: Player can join the server when repair mode on